root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -buildvcs=false -o tmp/main ."
bin = "tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
include_dir = ["."]
exclude_dir = ["tmp", "vendor"]

[log]
time = true
